services:
  - type: web
    name: my-react-app
    env: node
    buildCommand: |
      npm install
      npm install -g serve
      npm run build
    startCommand: serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NPM_CONFIG_PRODUCTION
        value: false 